baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"

theme = "reveal-hugo"

disableKinds = ["taxonomy", "taxonomyTerm"]

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
custom_theme = "presentation.scss"
custom_theme_compile = true
width = 1080
height = 788
plugins = ['js/typed.js']
